apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: use-mtls-on-sleep
spec:
  host: httpbin.rbac-scope-test.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
