apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: httpbin-viewer
  namespace: rbac-scope-test
spec:
  rules:
  - services: ["httpbin.rbac-scope-test.svc.cluster.local"]
    methods: ["GET"]
