apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    app: session-db
spec:
  ports:
  - port: 6379
    name: tcp
  clusterIP: None
  selector:
    app: session-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: session-db
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      app: session-db
  serviceName: session-db
  replicas: 1
  template:
    metadata:
      labels:
        app: session-db
        version: v1
    spec:
      containers:
      - name: session-db
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
